spring.application.name=schoolmanagement

spring.security.user.name=admin
spring.security.user.password=admin

spring.output.ansi.enabled=ALWAYS

#DATABASE CONNECTION
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=School_Management;encrypt=true;trustServerCertificate=true;
spring.datasource.username=school_mgmt
spring.datasource.password=school_mgmt
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver


#LOG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=ERROR
logging.level.org.hibernate.type=TRACE







