spring.application.name=schoolmanagement
spring.output.ansi.enabled=ALWAYS
management.security.cors.allowed-origins=http://localhost:4200
management.endpoints.web.exposure.include=health, heapdump, metrics, scheduledtasks
spring.data.web.pageable.max-page-size=100

#DATABASE CONNECTION
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=school_management_auto;encrypt=true;trustServerCertificate=true;
spring.datasource.username=school_mgmt
spring.datasource.password=school_mgmt
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

#FLYWAY
spring.flyway.url = jdbc:sqlserver://localhost:1433;databaseName=school_management_auto;encrypt=true;trustServerCertificate=true;
spring.flyway.password=school_mgmt
spring.flyway.user=school_mgmt

#HIBERNATE
spring.jpa.hibernate.ddl-auto=none

#LOG
logging.level.org.springframework.security=ERROR
logging.level.org.springframework.web=ERROR
logging.level.org.springframework.boot.autoconfigure=ERROR

lombok.addLombokGeneratedAnnotation = true

server.error.include-message=always


##### APPLICATION VALUES #####

#every 5th minute
attendance.init.task.cron=0 */5 * * * *

attendance.init.acceptable.schedule.statuses=SCHEDULED,RESCHEDULED,UPDATED
schedule.cancel.excluded.statuses=CANCELLED,DELETED
schedule.update.excluded.statuses=CANCELLED,DELETED

#every day at 02:00 AM
schedule.occurrence.init.cron=0 0 2 * * *
#every 3 hours
schedule.occurrence.complete.cron=0 0 */3 * * *