spring.application.name=schoolmanagement

spring.security.user.name=admin
spring.security.user.password=admin

spring.output.ansi.enabled=ALWAYS

#DATABASE CONNECTION
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=school_management_auto;encrypt=true;trustServerCertificate=true;
spring.datasource.username=school_mgmt
spring.datasource.password=school_mgmt
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

#FLYWAY
spring.flyway.url = jdbc:sqlserver://localhost:1433;databaseName=school_management_auto;encrypt=true;trustServerCertificate=true;
spring.flyway.password=school_mgmt
spring.flyway.user=school_mgmt

#HIBERNATE
spring.jpa.hibernate.ddl-auto=none

#LOG
logging.level.org.springframework.security=ERROR
logging.level.org.springframework.web=ERROR
logging.level.org.springframework.boot.autoconfigure=ERROR

lombok.addLombokGeneratedAnnotation = true

server.error.include-message=always


